# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Station.destroy_all
Bike.destroy_all
User.destroy_all
UserBike.destroy_all


darwin = Station.create(station_name:"Darwin Bikeshares Station", location:"34982 Darwin Way", photo_url:"http://i.imgur.com/DvAJYjq.png")
green = Station.create(station_name:"Green Bikeshares Station", location:"2469 Green Ridge Road", photo_url:"http://i.imgur.com/DvAJYjq.png")
elka = Station.create(station_name:"Elka Bikeshares Station", location:"5145 Elka Circle", photo_url:"http://i.imgur.com/DvAJYjq.png")
bunker = Station.create(station_name:"Bunker Hill Bikeshares Station", location:"2889 Bunker Hill Circle", photo_url:"http://i.imgur.com/DvAJYjq.png")
holy = Station.create(station_name:"Holy Cross Bikeshares Station", location:"80863 Holy Cross Center", photo_url:"http://i.imgur.com/DvAJYjq.png")
cambridge = Station.create(station_name:"Cambridge Bikeshares Station", location:"362 Cambridge Terrace", photo_url:"http://i.imgur.com/DvAJYjq.png")

mcGilvary = User.create(name:"Blondell McGilvary", membership:"annual", address:"9394 Calypso Center")
croney = User.create(name:"Giraud Croney", membership:"annual", address:"61658 Clarendon Park")
barhims = User.create(name:"Davida Barhims", membership:"annual", address:"5263 Morrow Drive")
goulborn = User.create(name:"Ardyth Goulborn", membership:"annual", address:"83616 Pearson Terrace")
goulborn = User.create(name:"Cyril Manginot", membership:"annual", address:"50 Amoth Parkway")
mcGilvary = User.create(name:"Avrom Pulhoster", membership:"annual", address:"13543 Morning Parkway")
mcGilvary = User.create(name:"Colette Janodet", membership:"annual", address:"5931 Truax Crossing")
easterling = User.create(name:"Sasha Easterling", membership:"annual", address:"42227 Heffernan Park")
kless = User.create(name:"Trumann Kless", membership:"annual", address:"77112 Debs Parkway")
roofe = User.create(name:"Marquita Roofe", membership:"annual", address:"717 Morningstar Junction")
jaksic = User.create(name:"Monty Jaksic", membership:"annual", address:"9186 Harbort Pass")
folcarelli = User.create(name:"Simona Folcarelli", membership:"monthly", address:"7129 Walton Terrace")
wordsley = User.create(name:"Derrek Wordsley", membership:"monthly", address:"5632 Boyd Drive")
yvon = User.create(name:"Avery Yvon", membership:"monthly", address:"45147 Bunker Hill Parkway")
sobey = User.create(name:"Lee Sobey", membership:"monthly", address:"66236 Park Meadow Way")
toner = User.create(name:"Abdul Toner", membership:"monthly", address:"9733 Talisman Parkway")
treadwell = User.create(name:"Rodger Treadwell", membership:"monthly", address:"5087 Dorton Center")
mozes = User.create(name:"Mozes O'Hartnedy", membership:"monthly", address:"9 Tony Center")
paulino = User.create(name:"Benedetta Paulino", membership:"monthly", address:"05 Golf Plaza")
miles = User.create(name:"Ruthie Miles", membership:"monthly", address:"6 Logan Hill")
audry = User.create(name:"Brennan Audry", membership:"monthly", address:"41 Village Junction")
kliement = User.create(name:"Cindi Kliement", membership:"monthly", address:"7 Utah Drive")
chaves = User.create(name:"Dougy Chaves", membership:"monthly", address:"9381 Becker Road")
delacourt = User.create(name:"Britt Delacourt", membership:"monthly", address:"57 Merchant Court")
delacourt = User.create(name:"Ebenezer Grassi", membership:"monthly", address:"61 Burrows Crossing")
rudinger = User.create(name:"Desirae Rudinger", membership:"monthly", address:"8 Comanche Plaza")
beynke = User.create(name:"Munmro Beynke", membership:"monthly", address:"7 Spaight Lane")
livoir = User.create(name:"Josh Livoir", membership:"daily", address:"9421 Lyons Lane")
haylor = User.create(name:"Ignaz Haylor", membership:"daily", address:"7429 Hauk Circle")
leiden = User.create(name:"Leonerd Leiden", membership:"daily", address:"3 Laurel Parkway")
sommerscales = User.create(name:"Kayne Sommerscales", membership:"daily", address:"4 Kennedy Way")
garrud = User.create(name:"Margie Garrud", membership:"daily", address:"9202 3rd Junction")
eberst = User.create(name:"Donnie Eberst", membership:"daily", address:"2 Quincy Crossing")
greasley = User.create(name:"Sharity Greasley", membership:"daily", address:"63 Hovde Hill")
firidolfi = User.create(name:"Florian Firidolfi", membership:"daily", address:"2 Reindahl Terrace")
firidolfi = User.create(name:"Henrieta Rendell", membership:"daily", address:"51275 Huxley Place")
lints = User.create(name:"Elroy Lints", membership:"daily", address:"6 High Crossing Court")
balser = User.create(name:"Edithe Balser", membership:"daily", address:"438 Ludington Park")
couche = User.create(name:"Kissiah Couche", membership:"daily", address:"2 2nd Crossing")
satch = User.create(name:"Jessi Satch", membership:"daily", address:"88 Dorton Court")
swindley = User.create(name:"Tobin Swindley", membership:"daily", address:"480 Cambridge Lane")
dows = User.create(name:"Fallon Dows", membership:"daily", address:"6257 Spohn Way")
mchugh = User.create(name:"Grethel McHugh", membership:"daily", address:"734 Hoepker Point")
yarrell = User.create(name:"Alyss Yarrell", membership:"daily", address:"5 Loeprich Pass")
hendrich = User.create(name:"Clywd Hendrich", membership:"daily", address:"81052 Macpherson Parkway")
doleman = User.create(name:"Demetre Doleman", membership:"daily", address:"6274 Sunnyside Trail")
slad = User.create(name:"Katalin Slad", membership:"daily", address:"740 Ruskin Lane")
elward = User.create(name:"Leighton Elward", membership:"daily", address:"5 Eliot Parkway")
bouchier = User.create(name:"Alexander Bouchier", membership:"daily", address:"7 Nelson Alley")
koschek = User.create(name:"Margaretha Koschek", membership:"daily", address:"214 Old Shore Street")

abc = Bike.create(serial_no:"sn426972747", bike_type:"bmx", model:"Tern", station:darwin)
bcd = Bike.create(serial_no:"sn3444167083", bike_type:"bmx", model:"Tern", station:darwin)
cde = Bike.create(serial_no:"sn3371891674", bike_type:"bmx", model:"Tern", station:darwin)
deff = Bike.create(serial_no:"sn4305002779", bike_type:"bmx", model:"Tern", station:darwin)
efg = Bike.create(serial_no:"sn8522507120", bike_type:"bmx", model:"Tern", station:darwin)
fgh = Bike.create(serial_no:"sn5716520340", bike_type:"mountain", model:"Terrot", station:green)
ghi = Bike.create(serial_no:"sn5813930531", bike_type:"mountain", model:"Terrot", station:green)
hij = Bike.create(serial_no:"sn3971464874", bike_type:"mountain", model:"Terrot", station:green)
ijk = Bike.create(serial_no:"sn1833401190", bike_type:"mountain", model:"Terrot", station:green)
jkl = Bike.create(serial_no:"sn3965506234", bike_type:"mountain", model:"Terrot", station:green)
klm = Bike.create(serial_no:"sn8864902651", bike_type:"racing", model:"Thomas", station:elka)
lnm = Bike.create(serial_no:"sn3624751034", bike_type:"racing", model:"Thomas", station:elka)
nmo = Bike.create(serial_no:"sn1034087967", bike_type:"racing", model:"Thomas", station:elka)
mno = Bike.create(serial_no:"sn7066350383", bike_type:"racing", model:"Thomas", station:elka)
nop = Bike.create(serial_no:"sn5131978149", bike_type:"racing", model:"Thomas", station:elka)
opq = Bike.create(serial_no:"sn2797419995", bike_type:"touring", model:"Thorn", station:bunker)
pqr = Bike.create(serial_no:"sn9416289272", bike_type:"touring", model:"Thorn", station:bunker)
qrs = Bike.create(serial_no:"sn9797990516", bike_type:"touring", model:"Thorn", station:bunker)
rst = Bike.create(serial_no:"sn4430326029", bike_type:"touring", model:"Thorn", station:bunker)
stu = Bike.create(serial_no:"sn1505278406", bike_type:"touring", model:"Thorn", station:bunker)
tuv = Bike.create(serial_no:"sn2119384754", bike_type:"hybrid", model:"Time", station:holy)
uvw = Bike.create(serial_no:"sn9640760641", bike_type:"hybrid", model:"Time", station:holy)
vwx = Bike.create(serial_no:"sn1605934070", bike_type:"hybrid", model:"Time", station:holy)
wxy = Bike.create(serial_no:"sn4087804860", bike_type:"hybrid", model:"Time", station:holy)
xyz = Bike.create(serial_no:"sn6807021213", bike_type:"hybrid", model:"Time", station:holy)
yza = Bike.create(serial_no:"sn5433855430", bike_type:"cruiser", model:"Titus", station:cambridge)
zab = Bike.create(serial_no:"sn1687001022", bike_type:"cruiser", model:"Titus", station:cambridge)
zbc = Bike.create(serial_no:"sn7772820852", bike_type:"cruiser", model:"Titus", station:cambridge)
zcd = Bike.create(serial_no:"sn1322655251", bike_type:"cruiser", model:"Titus", station:cambridge)
zde = Bike.create(serial_no:"sn3409688366", bike_type:"cruiser", model:"Titus", station:cambridge)

mcGilvary_abc = UserBike.create(user:mcGilvary, bike:abc, date_rented: "2017-06-11 12:37:00.757182-04", isReturned: false)
