# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Station.destroy_all
Bike.destroy_all
User.destroy_all
Userbike.destroy_all


darwin = Station.create(station_name:"Darwin Bikeshares Station", location:"34982 Darwin Way", photo_url:"http://i.imgur.com/DvAJYjq.png")
green = Station.create(station_name:"Green Bikeshares Station", location:"2469 Green Ridge Road", photo_url:"http://i.imgur.com/DvAJYjq.png")
elka = Station.create(station_name:"Elka Bikeshares Station", location:"5145 Elka Circle", photo_url:"http://i.imgur.com/DvAJYjq.png")
bunker = Station.create(station_name:"Bunker Hill Bikeshares Station", location:"2889 Bunker Hill Circle", photo_url:"http://i.imgur.com/DvAJYjq.png")
holy = Station.create(station_name:"Holy Cross Bikeshares Station", location:"80863 Holy Cross Center", photo_url:"http://i.imgur.com/DvAJYjq.png")
cambridge = Station.create(station_name:"Cambridge Bikeshares Station", location:"362 Cambridge Terrace", photo_url:"http://i.imgur.com/DvAJYjq.png")

abc = Bike.create(serial_no:"878-30-9745", bike_type:"CYCLOCROSS", model:"Tern model", station:darwin)
bcd = Bike.create(serial_no:"107-31-9682", bike_type:"CYCLOCROSS", model:"Tern model", station:darwin)
cde = Bike.create(serial_no:"147-53-2862", bike_type:"CYCLOCROSS", model:"Tern model", station:darwin)
deff = Bike.create(serial_no:"267-91-6287", bike_type:"CYCLOCROSS", model:"Tern model", station:darwin)
efg = Bike.create(serial_no:"121-09-2696", bike_type:"CYCLOCROSS", model:"Tern model", station:darwin)
fgh = Bike.create(serial_no:"803-11-0625", bike_type:"MOUNTAIN", model:"Terrot model", station:green)
ghi = Bike.create(serial_no:"237-93-2370", bike_type:"MOUNTAIN", model:"Terrot model", station:green)
hij = Bike.create(serial_no:"574-01-1738", bike_type:"MOUNTAIN", model:"Terrot model", station:green)
ijk = Bike.create(serial_no:"501-60-0844", bike_type:"MOUNTAIN", model:"Terrot model", station:green)
jkl = Bike.create(serial_no:"999-92-9427", bike_type:"MOUNTAIN", model:"Terrot model", station:green)
klm = Bike.create(serial_no:"443-99-5829", bike_type:"RACING", model:"Thomas model", station:elka)
lnm = Bike.create(serial_no:"350-01-8955", bike_type:"RACING", model:"Thomas model", station:elka)
nmo = Bike.create(serial_no:"656-88-3052", bike_type:"RACING", model:"Thomas model", station:elka)
mno = Bike.create(serial_no:"438-58-7729", bike_type:"RACING", model:"Thomas model", station:elka)
nop = Bike.create(serial_no:"534-13-3048", bike_type:"RACING", model:"Thomas model", station:elka)
opq = Bike.create(serial_no:"483-08-4225", bike_type:"TOURING", model:"Thorn model", station:bunker)
pqr = Bike.create(serial_no:"679-02-9172", bike_type:"TOURING", model:"Thorn model", station:bunker)
qrs = Bike.create(serial_no:"396-85-5314", bike_type:"TOURING", model:"Thorn model", station:bunker)
rst = Bike.create(serial_no:"997-73-6304", bike_type:"TOURING", model:"Thorn model", station:bunker)
stu = Bike.create(serial_no:"215-48-7524", bike_type:"TOURING", model:"Thorn model", station:bunker)
tuv = Bike.create(serial_no:"389-54-5046", bike_type:"HYBRID", model:"Time model", station:holy)
uvw = Bike.create(serial_no:"448-38-3063", bike_type:"HYBRID", model:"Time model", station:holy)
vwx = Bike.create(serial_no:"527-95-9864", bike_type:"HYBRID", model:"Time model", station:holy)
wxy = Bike.create(serial_no:"616-89-0215", bike_type:"HYBRID", model:"Time model", station:holy)
xyz = Bike.create(serial_no:"137-69-2064", bike_type:"HYBRID", model:"Time model", station:holy)
yza = Bike.create(serial_no:"465-56-3401", bike_type:"CRUISER", model:"Titus model", station:cambridge)
zab = Bike.create(serial_no:"614-34-3301", bike_type:"CRUISER", model:"Titus model", station:cambridge)
zbc = Bike.create(serial_no:"654-15-3183", bike_type:"CRUISER", model:"Titus model", station:cambridge)
zcd = Bike.create(serial_no:"435-79-3491", bike_type:"CRUISER", model:"Titus model", station:cambridge)
zde = Bike.create(serial_no:"262-25-2649", bike_type:"CRUISER", model:"Titus model", station:cambridge)

fitssum = User.create!(name:"Fitssum Haile", membership:"annual", address:"2904 Fairland rd.", email:"fitsum.wolde@gmail.com", password:"123456" )
mcGilvary = User.create!(name:"Blondell McGilvary", membership:"annual", address:"9394 Calypso Center", email:"bondell@yahoo.com", password:"123456")
croney = User.create!(name:"Giraud Croney", membership:"annual", address:"61658 Clarendon Park",  email:"pmorse1@cbsnews.com", password:"123456")
barhims = User.create!(name:"Davida Barhims", membership:"annual", address:"5263 Morrow Drive", email:"jdaughtrey2@gov.uk", password:"123456")
goulborn = User.create!(name:"Ardyth Goulborn", membership:"annual", address:"83616 Pearson Terrace", email:"skrink3@amazon.co.jp", password:"123456")
manginot = User.create!(name:"Cyril Manginot", membership:"annual", address:"50 Amoth Parkway", email:"rcrowch4@netlog.com", password:"123456")
mcGilvary = User.create!(name:"Avrom Pulhoster", membership:"annual", address:"13543 Morning Parkway", email:"neuston5@multiply.com", password:"123456")
mcGilvary = User.create!(name:"Colette Janodet", membership:"annual", address:"5931 Truax Crossing", email:"cwesley6@upenn.edu", password:"123456")
easterling = User.create!(name:"Sasha Easterling", membership:"annual", address:"42227 Heffernan Park", email:"fsalisbury7@google.co.uk", password:"123456")
kless = User.create!(name:"Trumann Kless", membership:"annual", address:"77112 Debs Parkway", email:"gpattinson8@lycos.com", password:"123456")
roofe = User.create!(name:"Marquita Roofe", membership:"annual", address:"717 Morningstar Junction", email:"dhansard9@miitbeian.gov.cn", password:"123456")
jaksic = User.create!(name:"Monty Jaksic", membership:"annual", address:"9186 Harbort Pass", email:"dbaumaiera@cyberchimps.com", password:"123456")
folcarelli = User.create!(name:"Simona Folcarelli", membership:"monthly", address:"7129 Walton Terrace", email:"aarmitb@digg.com", password:"123456")
wordsley = User.create!(name:"Derrek Wordsley", membership:"monthly", address:"5632 Boyd Drive", email:"aerickssenc@themeforest.net", password:"123456")
yvon = User.create!(name:"Avery Yvon", membership:"monthly", address:"45147 Bunker Hill Parkway", email:"imathetd@auda.org.au", password:"123456")
sobey = User.create!(name:"Lee Sobey", membership:"monthly", address:"66236 Park Meadow Way", email:"gdavione@engadget.com", password:"123456")
toner = User.create!(name:"Abdul Toner", membership:"monthly", address:"9733 Talisman Parkway", email:"mvaterf@google.co.jp", password:"123456")
treadwell = User.create!(name:"Rodger Treadwell", membership:"monthly", address:"5087 Dorton Center", email:"eeddisg@foxnews.com", password:"123456")
mozes = User.create!(name:"Mozes O'Hartnedy", membership:"monthly", address:"9 Tony Center", email:"ematysh@sfgate.com", password:"123456")
paulino = User.create!(name:"Benedetta Paulino", membership:"monthly", address:"05 Golf Plaza", email:"ntauntoni@plala.or.jp", password:"123456")

mcGilvary_abc = Userbike.create(user:mcGilvary, bike:abc, dt_rented: "2017-06-11 12:37:00.757182-04", dt_returned: false)
fitssum_fgh = Userbike.create(user:fitssum, bike:fgh, dt_rented: "2017-06-12 12:37:00.757182-04", dt_returned: true)
croney_klm = Userbike.create(user:croney, bike:klm, dt_rented: "2017-06-13 12:37:00.757182-04", dt_returned: false)
barhims_opq = Userbike.create(user:barhims, bike:opq, dt_rented: "2017-06-14 12:37:00.757182-04", dt_returned: false)
goulborn_tuv = Userbike.create(user:goulborn, bike:tuv, dt_rented: "2017-06-15 12:37:00.757182-04", dt_returned: false)
manginot_yza = Userbike.create(user:manginot, bike:yza, dt_rented: "2017-06-16 12:37:00.757182-04", dt_returned: false)
